config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
  get 'logout' => 'devise/sessions#destroy'
  get 'login' => 'devise/sessions#create'
  end
  resources :breets
  root 'breets#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breet.rb
class Breet < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :breets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breets_controller.rb
class BreetsController < ApplicationController
  before_action :set_breet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /breets
  # GET /breets.json
  def index
    @breets = Breet.all.order("created_at DESC")
    @breet= Breet.new
  end

  # GET /breets/1
  # GET /breets/1.json
  def show
  end

  # GET /breets/new
  def new
    @breet = current_user.breets.build
    
  end

  # GET /breets/1/edit
  def edit
  end

  # POST /breets
  # POST /breets.json
  def create
    @breet = current_user.breets.build(breet_params)

    respond_to do |format|
      if @breet.save
        format.html { redirect_to root_path, notice: 'Breet was successfully created.' }
        format.json { render :show, status: :created, location: @breet }
      else
        format.html { render :new }
        format.json { render json: @breet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breets/1
  # PATCH/PUT /breets/1.json
  def update
    respond_to do |format|
      if @breet.update(breet_params)
        format.html { redirect_to @breet, notice: 'Breet was successfully updated.' }
        format.json { render :show, status: :ok, location: @breet }
      else
        format.html { render :edit }
        format.json { render json: @breet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breets/1
  # DELETE /breets/1.json
  def destroy
    @breet.destroy
    respond_to do |format|
      format.html { redirect_to breets_url, notice: 'Breet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breet
      @breet = Breet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breet_params
      params.require(:breet).permit(:breet)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    
    private 
    
    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end
    
    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breets_helper.rb
module BreetsHelper
end

app/views/breets/_feed.html.erb
<div class= 'column is-half'>
  <% if user_signed_in? %>
  <article class= 'media box'>
    <figure class='media-left'>
      <p class='image is-64x64'>
        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
      </p>
      
    </figure>
    <div class="media-content">
      <%= render 'breets/form' %>
    </div>
  </article>
  <% end %>

<% @breets.each do | breet | %>
  <div class="box">
    <article class="media">
  	  <div class="media-left">
  			<figure class="image is-64x64">
  				<%= gravatar_image_tag(breet.user.email, size: 64, alt: breet.user.name) %>
  			</figure>
  		</div>
  		<div class= 'media-content'>
  		  <div class= "content">
  		    <strong><%=breet.user.name%></strong><br />
  		    <small><%=breet.user.username%></small><br />
  		    <p><%= breet.breet %></p>
  		  </div>
  		  <% if user_signed_in? && current_user.id == breet.user_id %>
  		  <nav class="level">
  		    <div class= "level-left is-mobile">
  		      <%= link_to breet, class: "level-item" do %>
  		        <span class= "icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  		      <% end %>
  		      <%= link_to edit_breet_path(breet), class:'level-item' do %>
  		        <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  		      <% end %>
  		      <%= link_to breet, method: :delete, data: {confirm: 'Are you sure you want to delete this Breet?'} do %>
  		        <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  		      <% end %>
  		    </div>
  		  </nav>
  		  <% end %>
  		</div>
  	</article>
  </div>
  <% end %>
</div>

app/views/breets/_form.html.erb
<%= simple_form_for(@breet) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :breet, label: "Breet about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new Breet...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/breets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<% if user_signed_in? %>
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
					<% end %>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweeets</p>
						<p class="title is-6"><%= current_user.breets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/breets/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
		</a>
	</nav>
</div>

app/views/breets/_who-to-follow.html.erb
<div class= "column">
  <nav class="panel">
    <p class="panel-heading">Who to follow</p>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>William Turcious</strong>
                        <small>@Willy12</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Robert Jenkins</strong>
                        <small>@robj12</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
  </nav>
</div>

app/views/breets/edit.html.erb
<h1>Editing Breet</h1>

<%= render 'form' %>

<%= link_to 'Show', @breet %> |
<%= link_to 'Back', breets_path %>

app/views/breets/index.html.erb
<section class='section'>
  <div class='container'>
    <div class='columns'>
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/breets/new.html.erb
<h1>New Breet</h1>

<%= render 'form' %>

<%= link_to 'Back', breets_path %>

app/views/breets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Breet:</strong>
  <%= @breet.breet %>
</p>

<%= link_to 'Edit', edit_breet_path(@breet) %> |
<%= link_to 'Back', breets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Britter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <div class= 'notification is-primary global-notification'>
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class= 'notification is-danager global-notification'>
       <p class="alert"><%= alert %></p>
    </div>
  <% end %>
  
  <nav class= 'navbar is-info'>
    <div class= 'navbar-brand'>
      <%= link_to root_path, class: 'navbar-item' do %>
      <h1 class='title is-5'>Britter</h1>
  <% end %>
      <div class="navbar-burger">
             <p class='control'>
                <% if user_signed_in? %>
                <%= link_to 'New Breet', new_breet_path, class: 'button is-info is-inverted' %>
                <%= link_to current_user.name, edit_user_registration_path, class: 'button is-info' %>
                <%= link_to 'Sign Out', logout_path, data: {confirm: 'Are you sure'}, class: 'button is-danger is-inverted' %>
              </p>
                <% else %>
              <p class="control"><%= link_to 'Sign Up', new_user_registration_path, class:'button is-info is-inverted'%></p>
              <p class= "control">
                <%= link_to 'Sign In', login_path, class:'control button is-info is-inverted'%>
              </p>
              <% end %>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
      <div id='navbarExample' class='navbar-menu'>
        <div class='navbar-end'>
          <div class='navbar-item'>
            <div class='field is-grouped'>
              <p class='control'>
                <% if user_signed_in? %>
                <%= link_to 'New Breet', new_breet_path, class: 'button is-info is-inverted' %>
                <%= link_to current_user.name, edit_user_registration_path, class: 'button is-info' %>
                <%= link_to 'Sign Out', logout_path, data: {confirm: 'Are you sure'}, class: 'button is-danger is-inverted' %>
              </p>
                <% else %>
              <p class="control"><%= link_to 'Sign Up', new_user_registration_path, class:'button is-info is-inverted'%></p>
              <p class= "control">
                <%= link_to 'Sign In', login_path, class:'control button is-info is-inverted'%>
              </p>
              <% end %>
            </div>
          </div>
        </div>
      </div> 
    </div>
  </nav>
<%= yield %>

<br /><br /><br />
<center>&copy Britannia Dev</center>

</body>
</html>